# Generated by Django 5.1.3 on 2025-07-25 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 11, 46, 4, 887404)),
        ),
    ]
