# Generated by Django 5.1.3 on 2025-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapp', '0002_alter_blog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
